export const USER_LOGIN = 'app.auth/USER_LOGIN'
export const LOGIN_SUCCESS = 'app.auth/LOGIN_SUCCESS'
export const USER_SIGNUP = 'app.auth/USER_SIGNUP'
export const SIGNUP_SUCCESS = 'app.auth/SIGNUP_SUCCESS'
export const AUTH_FAILED = 'app.auth/AUTH_FAILED'
